### ISSUE TITLE
Compatibility with Cyclops xml recipe system

### ISSUE THREAD

**Issue by rubensworks** [CyclopsMC/FluidConverters#17]
Auto-generate predefined items for all registered fluid groups (like https://github.com/CyclopsMC/EvilCraft/blob/master-1.7/src/main/resources/assets/evilcraft/recipes/shaped.xml#L493-L495).
Some other way of defining those items might be possible as well, like for example an extension to the xml recipe system for adding NBT tags.

**Comment by immortaleeb** [comment]
I tried this in a separate branch: https://github.com/CyclopsMC/FluidConverters/tree/recipes
The biggest problem that keeps it from working is the fact that fluid groups are loaded on postInit, while recipes are loaded somewhere in on Init.

The way I see it there are 2 possible fixes:
1. Move parsing of fluid group configs before recipe loading, and only load the actual fluid groups (i.e. find fluids in the registry) after all recipes are loaded. The problem is that this could potentially register recipes for fluid converters that appear to be invalid fluid converters later due to e.g. the fluids in the fluid elements being ignored.
2. Ignore recipe loading in init step and/or (re)trigger recipe loading after postInit (i.e. after loading the fluid groups).

**Comment by rubensworks** [comment]
I would try to move recipes loading to postInit (on CyclopsCore level).
Before making the actual change, look if this doesn't break anything, EvilCraft should be the first mod to show any signs of breakage.

**Comment by immortaleeb** [comment]
Added in 6174b9d2609c74ab62c76a8a3758f0ce91a8de2a
