### ISSUE TITLE
[1.10.2] Recipe for Fluid Converter missing in JEI

### ISSUE THREAD

**Issue by Morpheus1101** [CyclopsMC/FluidConverters#25]
is the Fluid Converter meant to have a recipe?  JEI shows no recipe an i was wanting to use it to convert blood from Tinkers into EvilCraft blood to use in the Intergrated Dynamics Drying Basin

**Comment by rubensworks** [comment]
Yes, this should be the default recipe: https://github.com/CyclopsMC/FluidConverters/blob/594a223437c406522fa79b2d1f0d1d4d565ab74e/src/main/java/org/cyclops/fluidconverters/FluidConvertersRecipeHandler.java#L69-L77
With container being any container of a converted fluid.

It's possible that this broke because of the latest Forge fluid changes, I'll have to look into that.

**Comment by Morpheus1101** [comment]
This is using Forge *.2094

**Comment by Morpheus1101** [comment]
Ok, either im doing it wrong or the recipe is completely broken(tending to go with the 1st option)
![mmd](https://cloud.githubusercontent.com/assets/10524952/18834082/6515e934-8437-11e6-8814-904d4020507a.png)

**Comment by rubensworks** [comment]
Your recipe should be correct, so something must be broken on my end. I'll look into it. (Hopefully this evening)

**Comment by rubensworks** [comment]
Fixed as of 866c961a779c498b89255722d751c380dc99a8c2

Requested an MMD server update for this: https://github.com/MinecraftModDevelopment/MMD-Dev-Server/issues/209
